#!/usr/bin/env python3
"""
MindPaw 手势识别知识蒸馏管线

目标: 从开源手势模型蒸馏轻量 MLP (38→16→8→5)
      并导出 int8 量化 C 头文件供 ESP8266 推理。

流程:
  1. 加载手势数据集 (HaGRID / 自采集)
  2. 提取 38 维特征 (32-bin 强度直方图 + 6-bin 空间分布)
  3. 训练教师模型 (Random Forest 或小 CNN)
  4. 蒸馏训练学生 MLP (使用教师软标签)
  5. Int8 量化权重
  6. 导出为 C 头文件 (gesture_weights.h)

用法:
  python distill_gesture.py --dataset ./gesture_data --export ../src/gesture_weights.h

依赖:
  pip install torch numpy scikit-learn opencv-python tqdm

参考:
  Hinton, G., Vinyals, O., & Dean, J. (2015). Distilling the Knowledge
  in a Neural Network. arXiv:1503.02531
"""

import argparse
import numpy as np
import struct
import os

# ---------------- 配置 ----------------
FEATURE_DIM = 38
HIDDEN1 = 16
HIDDEN2 = 8
OUTPUT_DIM = 5

GESTURE_NAMES = ["none", "wave", "palm", "fist", "point"]

# 端侧特征提取 (与 gesture_nn.cpp 一致)
# 训练时在 PC 上模拟端侧特征计算
def extract_features(image_grayscale):
    """
    输入: 40×30 uint8 灰度图
    输出: 38 维特征向量 (32-bin hist + 6-bin spatial)
    """
    h, w = image_grayscale.shape
    assert h == 40 and w == 30, f"Expected 40x30, got {h}x{w}"

    # 32-bin 直方图
    hist, _ = np.histogram(image_grayscale.flatten(), bins=32, range=(0, 256))
    hist = np.clip(hist / 1200.0 * 255, 0, 255).astype(np.uint8)

    # 6-bin 空间分布 (3×2 网格)
    spatial = np.zeros(6, dtype=np.uint8)
    grid_rows, grid_cols = 3, 2
    row_step, col_step = h // grid_rows, w // grid_cols
    idx = 0
    for gr in range(grid_rows):
        for gc in range(grid_cols):
            patch = image_grayscale[gr*row_step:(gr+1)*row_step,
                                    gc*col_step:(gc+1)*col_step]
            spatial[idx] = np.mean(patch).astype(np.uint8)
            idx += 1

    return np.concatenate([hist, spatial]).astype(np.uint8)


# 学生 MLP 模型 (PyTorch)
# 架构: 38 → 16 (ReLU) → 8 (ReLU) → 5 (logits)
def create_student():
    import torch.nn as nn
    class StudentMLP(nn.Module):
        def __init__(self):
            super().__init__()
            self.fc1 = nn.Linear(FEATURE_DIM, HIDDEN1)
            self.relu1 = nn.ReLU()
            self.fc2 = nn.Linear(HIDDEN1, HIDDEN2)
            self.relu2 = nn.ReLU()
            self.fc3 = nn.Linear(HIDDEN2, OUTPUT_DIM)

        def forward(self, x):
            x = self.relu1(self.fc1(x))
            x = self.relu2(self.fc2(x))
            x = self.fc3(x)
            return x

        def get_quantized_weights(self):
            """获取 int8 量化后的权重和偏置"""
            def quantize(tensor):
                # int8 量化: 找到范围 [-128, 127]
                arr = tensor.detach().numpy()
                max_val = np.max(np.abs(arr)) + 1e-6
                scale = 127.0 / max_val
                quant = np.clip(np.round(arr * scale), -128, 127).astype(np.int8)
                return quant, scale

            w1, s1 = quantize(self.fc1.weight.data)
            b1, _ = quantize(self.fc1.bias.data)
            w2, s2 = quantize(self.fc2.weight.data)
            b2, _ = quantize(self.fc2.bias.data)
            w3, s3 = quantize(self.fc3.weight.data)
            b3, _ = quantize(self.fc3.bias.data)

            return {
                'w1': w1.flatten(), 'b1': b1.flatten(), 'scale1': s1,
                'w2': w2.flatten(), 'b2': b2.flatten(), 'scale2': s2,
                'w3': w3.flatten(), 'b3': b3.flatten(), 'scale3': s3,
            }

    return StudentMLP()


def export_to_c_header(weights, output_path):
    """将量化权重导出为 C 头文件"""
    def format_array(data, name, per_line=16):
        lines = [f"static const int8_t {name}[] = {{"]
        values = [str(int(x)) for x in data]
        for i in range(0, len(values), per_line):
            chunk = values[i:i+per_line]
            lines.append("    " + ", ".join(chunk) + ",")
        lines.append("};")
        return "\n".join(lines)

    header = """// Auto-generated by tools/distill_gesture.py
// DO NOT EDIT — Regenerate with: python tools/distill_gesture.py
#ifndef GESTURE_WEIGHTS_H
#define GESTURE_WEIGHTS_H

#include <Arduino.h>

"""
    header += format_array(weights['w1'], 'GESTURE_W1', 16) + "\n\n"
    header += format_array(weights['b1'], 'GESTURE_B1', 16) + "\n\n"
    header += format_array(weights['w2'], 'GESTURE_W2', 16) + "\n\n"
    header += format_array(weights['b2'], 'GESTURE_B2', 16) + "\n\n"
    header += format_array(weights['w3'], 'GESTURE_W3', 16) + "\n\n"
    header += format_array(weights['b3'], 'GESTURE_B3', 16) + "\n\n"

    # Scale factors (used for inference dequantization)
    header += f"static const float GESTURE_SCALES[] = {{\n"
    header += f"    {weights['scale1']:.6f}f, {weights['scale2']:.6f}f, {weights['scale3']:.6f}f\n}};\n\n"
    header += "#endif // GESTURE_WEIGHTS_H\n"

    with open(output_path, 'w') as f:
        f.write(header)
    print(f"Exported weights to {output_path}")
    print(f"  w1: {len(weights['w1'])} int8 ({FEATURE_DIM}×{HIDDEN1})")
    print(f"  w2: {len(weights['w2'])} int8 ({HIDDEN1}×{HIDDEN2})")
    print(f"  w3: {len(weights['w3'])} int8 ({HIDDEN2}×{OUTPUT_DIM})")


def main():
    parser = argparse.ArgumentParser(description='Gesture Recognition Knowledge Distillation')
    parser.add_argument('--dataset', type=str, default='./gesture_data',
                       help='Path to gesture dataset (images organized by class)')
    parser.add_argument('--export', type=str, default='../src/gesture_weights.h',
                       help='Output path for C header')
    parser.add_argument('--epochs', type=int, default=100,
                       help='Student training epochs')
    parser.add_argument('--temperature', type=float, default=3.0,
                       help='Distillation temperature')
    parser.add_argument('--lr', type=float, default=0.001,
                       help='Student learning rate')
    args = parser.parse_args()

    print("=" * 50)
    print("MindPaw Gesture Distillation Pipeline")
    print("=" * 50)

    # Step 1: 检查数据集
    if not os.path.exists(args.dataset):
        print(f"\n[WARNING] Dataset not found at {args.dataset}")
        print("Creating simulated data for demonstration...")
        print("For real training, collect gesture images in subdirectories:")
        for name in GESTURE_NAMES:
            print(f"  {args.dataset}/{name}/")

        # 使用模拟数据演示蒸馏流程
        np.random.seed(42)
        from sklearn.ensemble import RandomForestClassifier

        N_SAMPLES = 500
        X = np.random.randint(0, 256, (N_SAMPLES, FEATURE_DIM), dtype=np.uint8)
        y = np.random.randint(0, OUTPUT_DIM, N_SAMPLES)

        print(f"\nStep 1: Using {N_SAMPLES} simulated samples")
    else:
        print(f"\nStep 1: Loading dataset from {args.dataset}")
        # 这里添加真实数据集加载代码
        # 期望目录结构:
        #   dataset/none/*.jpg
        #   dataset/wave/*.jpg
        #   ...
        from sklearn.model_selection import train_test_split
        import cv2

        X, y = [], []
        for label, name in enumerate(GESTURE_NAMES):
            class_dir = os.path.join(args.dataset, name)
            if not os.path.isdir(class_dir):
                continue
            for img_file in os.listdir(class_dir):
                if not img_file.lower().endswith(('.jpg', '.png', '.jpeg')):
                    continue
                img_path = os.path.join(class_dir, img_file)
                img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                if img is None:
                    continue
                img = cv2.resize(img, (30, 40))  # 40x30
                features = extract_features(img)
                X.append(features)
                y.append(label)

        X = np.array(X)
        y = np.array(y)
        print(f"  Loaded {len(X)} samples")

    # Step 2: 特征工程 (已经提取好了)
    print(f"\nStep 2: Features ready ({FEATURE_DIM} dim, {len(X)} samples)")
    print(f"  Class distribution: {np.bincount(y)}")

    # Step 3: 训练教师模型
    print(f"\nStep 3: Training teacher (Random Forest)...")
    teacher = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42)
    teacher.fit(X, y)
    teacher_acc = teacher.score(X, y)
    print(f"  Teacher accuracy: {teacher_acc:.3f}")

    # 获取教师软标签 (概率分布)
    teacher_soft = teacher.predict_proba(X)  # [N, 5]
    # 应用温度缩放
    teacher_soft = np.log(teacher_soft + 1e-8) / args.temperature
    teacher_soft = np.exp(teacher_soft) / np.sum(np.exp(teacher_soft), axis=1, keepdims=True)
    print(f"  Teacher soft labels shape: {teacher_soft.shape}")

    # Step 4: 蒸馏训练学生 MLP
    print(f"\nStep 4: Distilling student MLP ({FEATURE_DIM}→{HIDDEN1}→{HIDDEN2}→{OUTPUT_DIM})...")
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import TensorDataset, DataLoader

    # 数据归一化
    X_norm = X.astype(np.float32) / 128.0 - 1.0  # [-1, 1]

    dataset = TensorDataset(
        torch.from_numpy(X_norm),
        torch.from_numpy(y),
        torch.from_numpy(teacher_soft.astype(np.float32))
    )
    loader = DataLoader(dataset, batch_size=32, shuffle=True)

    student = create_student()
    optimizer = optim.Adam(student.parameters(), lr=args.lr)
    ce_loss = nn.CrossEntropyLoss()
    kl_loss = nn.KLDivLoss(reduction='batchmean')

    for epoch in range(args.epochs):
        total_loss = 0.0
        for batch_x, batch_y, batch_soft in loader:
            optimizer.zero_grad()
            logits = student(batch_x)

            # 蒸馏损失: hard label CE + soft label KL
            loss_hard = ce_loss(logits, batch_y)
            log_soft = nn.functional.log_softmax(logits / args.temperature, dim=1)
            loss_soft = kl_loss(log_soft, batch_soft)
            loss = 0.3 * loss_hard + 0.7 * loss_soft

            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        if (epoch + 1) % 20 == 0:
            print(f"  Epoch [{epoch+1}/{args.epochs}] Loss: {total_loss/len(loader):.4f}")

    # 评估学生
    student.eval()
    with torch.no_grad():
        logits = student(torch.from_numpy(X_norm))
        preds = torch.argmax(logits, dim=1).numpy()
        student_acc = np.mean(preds == y)
    print(f"  Student accuracy: {student_acc:.3f}")

    # Step 5: Int8 量化
    print(f"\nStep 5: Quantizing to int8...")
    quantized = student.get_quantized_weights()
    for name in ['w1', 'b1', 'w2', 'b2', 'w3', 'b3']:
        arr = quantized[name]
        print(f"  {name}: [{np.min(arr)}..{np.max(arr)}] ({len(arr)} int8)")

    # Step 6: 导出 C 头文件
    print(f"\nStep 6: Exporting to {args.export}")
    export_to_c_header(quantized, args.export)

    # 输出到 gesture_nn.cpp 的权重表单 (供参考)
    print(f"\n{'='*50}")
    print(f"To use these weights, replace the placeholder weights")
    print(f"in src/gesture_nn.cpp with the generated header.")
    print(f"Training complete! Model accuracy: {student_acc:.3f}")
    print(f"{'='*50}")


if __name__ == '__main__':
    main()
